version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "ezzy1630"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "rusqlite"
        versions:
          - ">= 0.40.0"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "ezzy1630"
    labels:
      - "dependencies"
