[package]
name = "argyph-pack"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
tiktoken-rs = "0.6"
camino = "1"

[dev-dependencies]
insta = "1"

[lib]
name = "argyph_pack"
path = "src/lib.rs"
