[package]
name = "argyph-memory"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
argyph-store = { path = "../argyph-store", version = "=1.0.0-rc.1" }
async-trait = "0.1"

[lib]
name = "argyph_memory"
path = "src/lib.rs"
