[package]
name = "argyph-graph"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
argyph-parse = { path = "../argyph-parse", version = "=1.0.4" }
camino = "1"
thiserror.workspace = true

[dev-dependencies]
argyph-fs = { path = "../argyph-fs", version = "=1.0.4" }

[lib]
name = "argyph_graph"
path = "src/lib.rs"
